# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CalQ(object):
    def setupUi(self, CalQ):
        CalQ.setObjectName("CalQ")
        CalQ.resize(360, 530)
        CalQ.setMinimumSize(QtCore.QSize(360, 530))
        CalQ.setMaximumSize(QtCore.QSize(360, 530))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Downloads/Circle-icons-calculator.svg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        CalQ.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(CalQ)
        self.centralwidget.setObjectName("centralwidget")
        self.button_one = QtWidgets.QPushButton(self.centralwidget)
        self.button_one.setGeometry(QtCore.QRect(0, 170, 90, 91))
        self.button_one.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.button_one.setObjectName("button_one")
        self.button_two = QtWidgets.QPushButton(self.centralwidget)
        self.button_two.setGeometry(QtCore.QRect(90, 170, 90, 91))
        self.button_two.setObjectName("button_two")
        self.button_three = QtWidgets.QPushButton(self.centralwidget)
        self.button_three.setGeometry(QtCore.QRect(180, 170, 90, 91))
        self.button_three.setObjectName("button_three")
        self.button_four = QtWidgets.QPushButton(self.centralwidget)
        self.button_four.setGeometry(QtCore.QRect(0, 260, 90, 91))
        self.button_four.setObjectName("button_four")
        self.button_bs = QtWidgets.QPushButton(self.centralwidget)
        self.button_bs.setGeometry(QtCore.QRect(270, 130, 90, 41))
        self.button_bs.setObjectName("button_bs")
        self.button_five = QtWidgets.QPushButton(self.centralwidget)
        self.button_five.setGeometry(QtCore.QRect(90, 260, 90, 91))
        self.button_five.setObjectName("button_five")
        self.button_seven = QtWidgets.QPushButton(self.centralwidget)
        self.button_seven.setGeometry(QtCore.QRect(0, 350, 90, 91))
        self.button_seven.setObjectName("button_seven")
        self.button_nine = QtWidgets.QPushButton(self.centralwidget)
        self.button_nine.setGeometry(QtCore.QRect(180, 350, 90, 91))
        self.button_nine.setObjectName("button_nine")
        self.button_eight = QtWidgets.QPushButton(self.centralwidget)
        self.button_eight.setGeometry(QtCore.QRect(90, 350, 90, 91))
        self.button_eight.setObjectName("button_eight")
        self.button_zero = QtWidgets.QPushButton(self.centralwidget)
        self.button_zero.setGeometry(QtCore.QRect(90, 440, 90, 91))
        self.button_zero.setObjectName("button_zero")
        self.button_x = QtWidgets.QPushButton(self.centralwidget)
        self.button_x.setGeometry(QtCore.QRect(270, 170, 90, 91))
        self.button_x.setObjectName("button_x")
        self.button_div = QtWidgets.QPushButton(self.centralwidget)
        self.button_div.setGeometry(QtCore.QRect(270, 260, 90, 91))
        self.button_div.setObjectName("button_div")
        self.button_plus = QtWidgets.QPushButton(self.centralwidget)
        self.button_plus.setGeometry(QtCore.QRect(270, 350, 90, 91))
        self.button_plus.setObjectName("button_plus")
        self.button_minus = QtWidgets.QPushButton(self.centralwidget)
        self.button_minus.setGeometry(QtCore.QRect(180, 440, 90, 91))
        self.button_minus.setObjectName("button_minus")
        self.button_eq = QtWidgets.QPushButton(self.centralwidget)
        self.button_eq.setGeometry(QtCore.QRect(270, 440, 90, 91))
        self.button_eq.setObjectName("button_eq")
        self.button_dot = QtWidgets.QPushButton(self.centralwidget)
        self.button_dot.setGeometry(QtCore.QRect(0, 440, 90, 91))
        self.button_dot.setObjectName("button_dot")
        self.calculate = QtWidgets.QLabel(self.centralwidget)
        self.calculate.setGeometry(QtCore.QRect(0, 20, 351, 91))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.calculate.setFont(font)
        self.calculate.setObjectName("calculate")
        self.button_six = QtWidgets.QPushButton(self.centralwidget)
        self.button_six.setGeometry(QtCore.QRect(180, 260, 90, 91))
        self.button_six.setObjectName("button_six")
        self.button_escape = QtWidgets.QPushButton(self.centralwidget)
        self.button_escape.setGeometry(QtCore.QRect(180, 130, 90, 41))
        self.button_escape.setObjectName("button_escape")
        self.button_lw = QtWidgets.QPushButton(self.centralwidget)
        self.button_lw.setGeometry(QtCore.QRect(0, 130, 90, 41))
        self.button_lw.setObjectName("button_lw")
        self.button_rw = QtWidgets.QPushButton(self.centralwidget)
        self.button_rw.setGeometry(QtCore.QRect(90, 130, 90, 41))
        self.button_rw.setObjectName("button_rw")
        CalQ.setCentralWidget(self.centralwidget)

        self.retranslateUi(CalQ)
        QtCore.QMetaObject.connectSlotsByName(CalQ)

    def retranslateUi(self, CalQ):
        _translate = QtCore.QCoreApplication.translate
        CalQ.setWindowTitle(_translate("CalQ", "CalQ"))
        self.button_one.setText(_translate("CalQ", "1"))
        self.button_two.setText(_translate("CalQ", "2"))
        self.button_three.setText(_translate("CalQ", "3"))
        self.button_four.setText(_translate("CalQ", "4"))
        self.button_bs.setText(_translate("CalQ", "<-"))
        self.button_five.setText(_translate("CalQ", "5"))
        self.button_seven.setText(_translate("CalQ", "7"))
        self.button_nine.setText(_translate("CalQ", "9"))
        self.button_eight.setText(_translate("CalQ", "8"))
        self.button_zero.setText(_translate("CalQ", "0"))
        self.button_x.setText(_translate("CalQ", "X"))
        self.button_div.setText(_translate("CalQ", "÷"))
        self.button_plus.setText(_translate("CalQ", "+"))
        self.button_minus.setText(_translate("CalQ", "-"))
        self.button_eq.setText(_translate("CalQ", "="))
        self.button_dot.setText(_translate("CalQ", "."))
        self.calculate.setText(_translate("CalQ", "CalQ v1.0"))
        self.button_six.setText(_translate("CalQ", "6"))
        self.button_escape.setText(_translate("CalQ", "ecs"))
        self.button_lw.setText(_translate("CalQ", "("))
        self.button_rw.setText(_translate("CalQ", ")"))
